### ISSUE TITLE
Running errors and parameter initialization problems

### ISSUE THREAD

**Issue by Yngjx** [befelix/safe_learning#10]
Hi Felix,
I have these questions.
I run lyapunov_function_learning.ipynb and got an error like this.
`ModuleNotFoundError: No module named 'safe_learning'`
And I don't quite understand how the initialization parameters of the Lyapunov function are obtained.
![D}M6)ETN131NH{IZCVWCDES](https://user-images.githubusercontent.com/114039587/191441041-40b9b132-2e82-457c-89a6-5475ede137c6.png)
1. In all the files, I did not find it.So where can I find this safe_learning module?
2. Could you please explain in detail how the parameter initialization is done?

**Comment by befelix** [comment]
This code is really old and I would not recommend using it anymore. That being said, `safe_learning` is the name of the module provided in this repo, see also the instruction in the main readme. Parameter initialization happens [here](https://github.com/befelix/safe_learning/blob/master/safe_learning/functions.py#L1708).

**Comment by Yngjx** [comment]
Thanks for your reply!
As you said, `safe_learning` is the name of the module provided in this repo, but I still want to find the definition of `safe_learning` to understand the code of this paper.
One more question, do you think the code can be reproduced in MATLAB?

**Comment by befelix** [comment]
I'm not sure I understand your question: the `safe_learning` module contains the paper code. All you need to do is to follow the installation instructions for it to be found.

Regarding matlab: I would assume it's possible, but it's been a very long time since I last used matlab.

**Comment by Yngjx** [comment]
What I mean is that I'm running your code with the error that the module `safe_learning` is missing, so I can't run your code properly, but I can't find this module in all your folders.

So what I want to know is how to find it and then run your code without any problem. I don't know if this makes sense to you.

I just want to run your code successfully to understand some of the ideas you have in your paper.

Thank you very much for reading!

**Comment by Yngjx** [comment]
This issue is described in the following figure.

![{M0GT{}YD2~CJ15NH$Y{8EX](https://user-images.githubusercontent.com/114039587/196652505-082b8a4d-3dfa-4938-9f2c-610b22be13e5.png)

**Comment by Yngjx** [comment]
I am very sorry!

Your previous answer to this question was clear enough, I was the one who didn't understand what you meant, now I figured it out.

Have a nice life!
