### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by hari-sikchi** [befelix/safe_learning#7]
I tried installing the package within a conda environment with the instructions given but failed.

EDIT: 
I managed to find an alternative way that works
```
conda create -new "safe_learning" python=3.6
conda activate safe_learning
conda install tensorflow==1.12.0
```
Remove the following lines from requirements.txt
1. numpy>=1.0,<1.15
2. tensorflow>=1.6.0,<=1.12.0

Do:
```
pip install pip==18.1
pip install . --process-dependency-links
```

On MacOS:
```
export KMP_DUPLICATE_LIB_OK=TRUE
```
The above should be done before running jupyter notebooks.

**Comment by befelix** [comment]
Did you find a solution on your own? My guess is that the problem is caused by a python version `>3.5`, which is the one the library is tested against. I've added this requirement to the readme.

**Comment by hari-sikchi** [comment]
Thanks for the update! Yes, i managed to get it working with the configuration mentioned above.
